name: Merge Feature a Main y Deploy a S3

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened ]

jobs:
  merge-feature-into-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      ########################################################
      # 1. Descargar c贸digo destino (main)
      ########################################################
      - name: Checkout destino (main)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      ########################################################
      # 2. Configurar usuario de Git
      ########################################################
      - name: Configurar usuario Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      ########################################################
      # 3. Hacer merge de feature branch
      ########################################################
      - name: Merge feature branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git merge --no-ff --verbose origin/${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.number }}"

      ########################################################
      # 4. Push de cambios
      ########################################################
      - name: Push cambios a main
        run: |
          git push origin ${{ github.base_ref }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: merge-feature-into-main
    if: ${{ success() }}

    steps:
      ########################################################
      # 5. Clonar repositorio
      ########################################################
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      ########################################################
      # 6. Verificar estructura de carpetas
      ########################################################
      - name: Verificar estructura de carpetas
        run: ls -a

      ########################################################
      # 7. Configurar Node.js
      ########################################################
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      ########################################################
      # 8. Instalar dependencias
      ########################################################
      - name: Instalar dependencias
        run: npm install

      - name: Create environment files
        run: npm run envs
        env:
          BASE_URL_DEV: ${{ secrets.BASE_URL_DEV }}
          BASE_URL_PROD: ${{ secrets.BASE_URL_PROD }}

      ########################################################
      # 9. Construir aplicaci贸n Angular
      ########################################################
      - name: Construir aplicaci贸n Angular
        run: npm run build

      ########################################################
      # 10. Configurar credenciales AWS
      ########################################################
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      ########################################################
      # 11. Subir archivos construidos a S3
      ########################################################
      - name: Subir archivos a S3
        run: |
          aws s3 sync dist/claimhere-front/browser/ ${{ secrets.AWS_SECRET_S3_PRD }} --delete
  
