name: Merge Feature a Develop y Copiar archivos S3 PRD

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]

jobs:
  merge-feature-into-develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      ########################################################
      # 1. Descargar código destino (develop)
      ########################################################
      - name: Checkout destino (develop)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      ########################################################
      # 2. Configurar usuario de Git
      ########################################################
      - name: Configurar usuario Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      ########################################################
      # 3. Hacer merge de feature branch
      ########################################################
      - name: Merge feature branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git merge --no-ff --verbose origin/${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.number }}"

      ########################################################
      # 4. Push de cambios
      ########################################################
      - name: Push cambios a develop
        run: |
          git push origin ${{ github.base_ref }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: merge-feature-into-develop
    if: ${{ success() }}
    steps:
      ########################################################
      # 5. Configurar credenciales AWS
      ########################################################
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      ########################################################
      # 6. Copiar archivos de QA a PRD
      ########################################################
      - name: Copiar archivos de S3 QA a S3 PRD
        run: |
          aws s3 cp s3://pruebaautomatizacion/ s3://legalcode-prd/ --recursive
