name: Deploy a QA a PRD en S3

on:
  workflow_dispatch:
    inputs:
      estado:
        description: 'Envia 1 para enviar a S3 de PRD'
        required: true
        default: '1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    # <<<< IMPORTANTE: steps debe ir dentro del job, no fuera
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Subir archivos de QA a PRD
        run: |
          aws s3 cp s3://pruebaautomatizacion/ s3://angular-prueba-2/ --recursive