name: Actualización de S3

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Usar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20 # O el que uses en tu proyecto

    - name: Instalar dependencias
      working-directory: ./frontend-claimhere
      run: npm install

    - name: Construir aplicación Angular
      working-directory: ./frontend-claimhere
      run: npm run build

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Subir archivos generados a S3
      run: |
        aws s3 sync ./frontend-claimhere/dist/claimhere-front/browser/ s3://pruebaautomatizacion/ --delete
